## Charging Time Prediction for Battery Electric Vehicles (BEVs) using Time Series Methods

## Project Overview
### Battery Electric Vehicles (BEVs) play a significant role in reducing energy consumption and air pollution, offering a cleaner alternative to conventional internal combustion engine vehicles. Despite their advantages, BEVs face challenges related to limited driving range and prolonged charging durations. These issues contribute to range anxiety, which significantly affects user adoption and satisfaction. Predicting charging time accurately based on real-world data can empower drivers with better travel planning and reduce anxiety. This project aims to develop a predictive model that improves the estimation of BEV charging times by leveraging actual operational data from BEVs

In [2]:
## Important libraries to import for data analysis and visualization
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline  

### Loading the data set 
### Basic data analysis
### Creating the copy of the dataset (df_copy)

In [3]:
df = pd.read_csv(r"./data/cadcs_live_project_clean_data.csv")
df_copy = df.copy() ## generated a copy of the original dataframe (df_copy)

In [281]:
df_copy.head(5)

,session_id,vehicle_id,user_id,start_time,end_time,charging_duration_min,energy_delivered_kwh,vehicle_make,vehicle_model,battery_capacity_kwh,...,charging_standard_compliance,safety_certification,session_type,booking_lead_time_min,session_rating,energy_efficiency_kwh_per_100km,week_of_year,day_of_year,is_month_end,is_quarter_end
0,IND_BEV_136287,MAH8558,USR_87015,01-01-2018 07:30,01-01-2018 08:09,38.366667,7.784,MAHINDRA,e2o Plus,15.0,...,IS_17017_Compliant,BIS_Certified,Scheduled,51.0,4.4,16.950283,1,1,False,False
1,IND_BEV_105860,TAT3386,USR_48693,01-01-2018 08:33,01-01-2018 10:58,145.000000,12.672,TATA,Tigor EV,26.0,...,IS_17017_Compliant,BIS_Certified,Opportunistic,95.0,4.4,16.950283,1,1,False,False
2,IND_BEV_145876,TVS7311,USR_15892,01-01-2018 09:48,01-01-2018 09:59,11.750000,1.406,TVS,X,4.4,...,IS_17017_Compliant,BIS_Certified,Scheduled,6.0,3.8,12.408844,1,1,False,False
3,IND_BEV_150791,BAJ2976,USR_99201,01-01-2018 10:16,01-01-2018 10:21,5.000000,0.642,BAJAJ,Urbanite,2.9,...,IS_17017_Compliant,BIS_Certified,Scheduled,81.0,4.7,12.408844,1,1,False,False
4,IND_BEV_121632,TAT8277,USR_31054,01-01-2018 11:44,01-01-2018 11:50,6.200000,12.512,TATA,Tiago EV,24.0,...,IS_17017_Compliant,BIS_Certified,Scheduled,13.0,4.1,16.950283,1,1,False,False


In [282]:
df.tail(10)

,session_id,vehicle_id,user_id,start_time,end_time,charging_duration_min,energy_delivered_kwh,vehicle_make,vehicle_model,battery_capacity_kwh,...,charging_standard_compliance,safety_certification,session_type,booking_lead_time_min,session_rating,energy_efficiency_kwh_per_100km,week_of_year,day_of_year,is_month_end,is_quarter_end
74933,IND_BEV_162189,TAT6169,USR_59191,31-12-2024 14:06,31-12-2024 14:19,12.866667,7.414,TATA,Tiago EV,24.0,...,IS_17017_Compliant,BIS_Certified,Opportunistic,13.0,3.7,16.950283,1,366,True,True
74934,IND_BEV_125373,HER4604,USR_74900,31-12-2024 14:35,31-12-2024 14:44,8.833333,0.547,HERO,Optima,1.8,...,IS_17017_Compliant,BIS_Certified,Scheduled,18.0,3.7,12.408844,1,366,True,True
74935,IND_BEV_171642,TAT6791,USR_53098,31-12-2024 14:52,31-12-2024 15:06,13.350000,5.965,TATA,Tigor EV,26.0,...,IS_17017_Compliant,BIS_Certified,Opportunistic,20.0,4.6,16.950283,1,366,True,True
74936,IND_BEV_161162,MAH5737,USR_74580,31-12-2024 16:43,31-12-2024 18:13,89.250000,7.399,MAHINDRA,eXUV300,34.5,...,IS_17017_Compliant,BIS_Certified,Opportunistic,6.0,4.3,16.950283,1,366,True,True
74937,IND_BEV_151196,TAT2571,USR_12166,31-12-2024 17:01,31-12-2024 19:41,159.783333,15.099,TATA,Nexon EV,40.5,...,IS_17017_Compliant,BIS_Certified,Scheduled,68.0,4.2,16.950283,1,366,True,True
74938,IND_BEV_126265,MAH5891,USR_99873,31-12-2024 18:19,31-12-2024 20:22,123.133333,13.600,MAHINDRA,eVerito,21.2,...,IS_17017_Compliant,BIS_Certified,Opportunistic,106.0,4.3,16.950283,1,366,True,True
74939,IND_BEV_116010,TVS9578,USR_75798,31-12-2024 18:53,31-12-2024 19:06,12.616667,3.237,TVS,X,4.4,...,IS_17017_Compliant,BIS_Certified,Opportunistic,118.0,4.6,12.408844,1,366,True,True
74940,IND_BEV_166151,BAJ2386,USR_11068,31-12-2024 20:32,31-12-2024 20:37,5.366667,0.629,BAJAJ,Urbanite,2.9,...,IS_17017_Compliant,BIS_Certified,Scheduled,30.0,4.2,12.408844,1,366,True,True
74941,IND_BEV_174026,MAH6729,USR_98840,31-12-2024 21:48,31-12-2024 22:40,51.600000,4.968,MAHINDRA,e2o Plus,15.0,...,IS_17017_Compliant,BIS_Certified,Opportunistic,69.0,3.8,16.950283,1,366,True,True
74942,IND_BEV_125407,HER7711,USR_16544,31-12-2024 21:55,31-12-2024 22:13,17.666667,1.040,HERO,Optima,1.8,...,IS_17017_Compliant,BIS_Certified,Opportunistic,53.0,4.6,12.408844,1,366,True,True


In [283]:
df_copy.shape,df_copy.size,df_copy.columns

((74943, 74),
 5545782,
 Index(['session_id', 'vehicle_id', 'user_id', 'start_time', 'end_time',
        'charging_duration_min', 'energy_delivered_kwh', 'vehicle_make',
        'vehicle_model', 'battery_capacity_kwh', 'vehicle_age_years',
        'battery_health_index', 'user_type', 'income_bracket', 'city', 'state',
        'latitude', 'longitude', 'charging_station_id', 'station_operator',
        'charger_type', 'charger_power_kw', 'plug_type', 'initial_soc_percent',
        'final_soc_percent', 'soc_gained_percent', 'day_of_week', 'hour_of_day',
        'month', 'season', 'is_weekend', 'is_peak_hour', 'festival',
        'ambient_temperature_c', 'humidity_percent', 'weather_condition',
        'air_quality_index', 'battery_temperature_c', 'grid_frequency_hz',
        'grid_reliability_index', 'power_quality_score', 'load_shedding_event',
        'grid_load_mw', 'tariff_per_kwh_inr', 'total_cost_inr',
        'subsidy_amount_inr', 'payment_method', 'payment_success_rate',
        '

In [284]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74943 entries, 0 to 74942
Data columns (total 74 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   session_id                       74943 non-null  object 
 1   vehicle_id                       74943 non-null  object 
 2   user_id                          74943 non-null  object 
 3   start_time                       74943 non-null  object 
 4   end_time                         74943 non-null  object 
 5   charging_duration_min            74943 non-null  float64
 6   energy_delivered_kwh             74943 non-null  float64
 7   vehicle_make                     74943 non-null  object 
 8   vehicle_model                    74943 non-null  object 
 9   battery_capacity_kwh             74943 non-null  float64
 10  vehicle_age_years                74943 non-null  int64  
 11  battery_health_index             74943 non-null  float64
 12  user_type         

In [285]:
df_copy.describe()

,charging_duration_min,energy_delivered_kwh,battery_capacity_kwh,vehicle_age_years,battery_health_index,latitude,longitude,charger_power_kw,initial_soc_percent,final_soc_percent,...,session_success_rate,user_satisfaction_score,distance_to_station_km,range_remaining_km,next_destination_distance_km,booking_lead_time_min,session_rating,energy_efficiency_kwh_per_100km,week_of_year,day_of_year
count,74943.000000,74943.000000,74943.000000,74943.000000,74943.000000,74943.000000,74943.000000,74943.000000,74943.000000,74943.000000,...,74943.000000,74943.000000,74943.000000,74943.000000,74943.000000,74943.000000,74943.000000,74943.000000,74943.000000,74943.000000
mean,62.271105,7.300049,18.934349,2.038643,0.944291,20.595023,77.624217,20.713981,31.216831,69.188503,...,0.965033,4.000306,2.468798,109.230059,14.872837,59.638399,4.248594,14.459985,26.481393,182.635363
std,87.426272,7.865827,18.975171,2.498549,0.053543,6.190951,4.113718,32.229080,12.419413,13.705514,...,0.014460,0.464787,2.392755,44.971961,14.896025,34.137732,0.434893,2.260093,15.046415,105.330960
min,5.000000,0.405000,1.800000,0.000000,0.650000,9.911208,72.551430,3.300000,10.000000,30.000000,...,0.940000,3.200000,0.000000,15.100000,0.000000,0.000000,3.500000,12.408844,1.000000,1.000000
25%,7.483333,1.070000,2.900000,0.000000,0.921000,17.365092,75.767815,5.000000,22.000000,59.000000,...,0.953000,3.600000,0.700000,75.500000,4.400000,31.000000,3.900000,12.408844,13.000000,92.000000
50%,21.200000,5.140000,15.000000,1.000000,0.956000,19.095024,77.190506,6.700000,29.000000,71.000000,...,0.965000,4.000000,1.700000,102.900000,10.300000,59.638400,4.200000,12.408844,26.000000,183.000000
75%,86.983333,10.970000,26.000000,3.000000,0.980000,26.865420,80.250885,17.600000,39.000000,79.000000,...,0.978000,4.400000,3.400000,137.900000,20.400000,89.000000,4.600000,16.950283,39.000000,274.000000
max,719.733333,38.524480,95.000000,26.000000,1.020000,28.633896,88.383900,150.000000,59.000000,100.000000,...,0.990000,4.800000,11.600000,226.400000,193.600000,119.000000,5.000000,16.950283,53.000000,366.000000


In [286]:
## Getting All Different Types OF Features
num_features = [feature for feature in df.columns if df[feature].dtype != 'O']
print('Num of Numerical Features :', len(num_features))
cat_features = [feature for feature in df.columns if df[feature].dtype == 'O']
print('Num of Categorical Features :', len(cat_features))
discrete_features=[feature for feature in num_features if len(df[feature].unique())<=25]
print('Num of Discrete Features :',len(discrete_features))
continuous_features=[feature for feature in num_features if feature not in discrete_features]
print('Num of Continuous Features :',len(continuous_features))
## Discrete Feature +continous Feature = Numerical feature 

Num of Numerical Features : 44
Num of Categorical Features : 30
Num of Discrete Features : 12
Num of Continuous Features : 32


In [25]:
## get all the numeric features
num_features = [feature for feature in df.columns if df[feature].dtype != 'O']
print('Num of Numerical Features :', len(num_features))

Num of Numerical Features : 44


In [27]:
## Discrete features but discrete features are also part of numerical features 
discrete_features=[feature for feature in num_features if len(df[feature].unique())<=25]
print('Num of Discrete Features :',len(discrete_features))

Num of Discrete Features : 12


In [29]:
discrete_features

['battery_capacity_kwh',
 'hour_of_day',
 'month',
 'is_weekend',
 'is_peak_hour',
 'grid_reliability_index',
 'subsidy_amount_inr',
 'user_satisfaction_score',
 'session_rating',
 'energy_efficiency_kwh_per_100km',
 'is_month_end',
 'is_quarter_end']

In [28]:
## Discrete features but discrete features are also part of numerical features 
continuous_features=[feature for feature in num_features if len(df[feature].unique())>25]
print('Num of  continuous Features :',len(continuous_features))

Num of  continuous Features : 32


In [26]:
## get all the numeric features
catagorical_features = [feature for feature in df.columns if df[feature].dtype == 'O']
print('Num of categorical Features :', len(catagorical_features))

Num of categorical Features : 30


In [287]:
categorical_features = df_copy.select_dtypes(include=['object']).columns.tolist()
numerical_features = df_copy.select_dtypes(include=['float64','int64']).columns.tolist()
yes_no_features = df_copy.select_dtypes(include=['bool']).columns.tolist()
print(df_copy.columns)
print(len(df_copy.columns))
print(categorical_features)
print(len(categorical_features))
print(numerical_features)
print(len(numerical_features))
print(yes_no_features)
print(len(yes_no_features))


Index(['session_id', 'vehicle_id', 'user_id', 'start_time', 'end_time',
       'charging_duration_min', 'energy_delivered_kwh', 'vehicle_make',
       'vehicle_model', 'battery_capacity_kwh', 'vehicle_age_years',
       'battery_health_index', 'user_type', 'income_bracket', 'city', 'state',
       'latitude', 'longitude', 'charging_station_id', 'station_operator',
       'charger_type', 'charger_power_kw', 'plug_type', 'initial_soc_percent',
       'final_soc_percent', 'soc_gained_percent', 'day_of_week', 'hour_of_day',
       'month', 'season', 'is_weekend', 'is_peak_hour', 'festival',
       'ambient_temperature_c', 'humidity_percent', 'weather_condition',
       'air_quality_index', 'battery_temperature_c', 'grid_frequency_hz',
       'grid_reliability_index', 'power_quality_score', 'load_shedding_event',
       'grid_load_mw', 'tariff_per_kwh_inr', 'total_cost_inr',
       'subsidy_amount_inr', 'payment_method', 'payment_success_rate',
       'station_congestion_level', 'queue_wait

In [288]:
## null values are present or not 
df.isnull().sum().sum()

0

In [4]:
df.isnull().sum()

session_id                         0
vehicle_id                         0
user_id                            0
start_time                         0
end_time                           0
                                  ..
energy_efficiency_kwh_per_100km    0
week_of_year                       0
day_of_year                        0
is_month_end                       0
is_quarter_end                     0
Length: 74, dtype: int64

In [24]:
df_copy['vehicle_model'].value_counts(normalize=True)*100 ## label encoding
df_copy['income_bracket'].value_counts(normalize=True)*100 ## ordinal 
df_copy['station_operator'].value_counts(normalize=True)*100 ## label 
df_copy['is_peak_hour'].value_counts(normalize=True)*100 ## label 
df_copy['load_shedding_event'].value_counts(normalize=True)*100 ## label 
df_copy['cooling_system_active'].value_counts(normalize=True)*100 ## label 
df_copy['thermal_management'].value_counts(normalize=True)*100 ## ordinal 
df_copy['user_type'].value_counts(normalize=True)*100 ## ohe
df_copy['charger_type'].value_counts(normalize=True)*100 ## ohe
df_copy['plug_type'].value_counts(normalize=True)*100 ## ohe
df_copy['weather_condition'].value_counts(normalize=True)*100 ## ohe
df_copy['session_type'].value_counts(normalize=True)*100 ## ohe
df_copy['station_congestion_level'].value_counts(normalize=True)*100 ## ordinal 
df_copy['season'].value_counts(normalize=True)*100 ## ohe


season
Summer          33.497458
Monsoon         25.280547
Winter          24.602698
Post_Monsoon    16.619297
Name: proportion, dtype: float64

In [289]:
## Duplicate values are present or not 
df[df.duplicated()]

,session_id,vehicle_id,user_id,start_time,end_time,charging_duration_min,energy_delivered_kwh,vehicle_make,vehicle_model,battery_capacity_kwh,...,charging_standard_compliance,safety_certification,session_type,booking_lead_time_min,session_rating,energy_efficiency_kwh_per_100km,week_of_year,day_of_year,is_month_end,is_quarter_end


### Our target variable is 'charging_duration_min' for this dataset ....................
### We are trying to dividing our data set into dependent and independent variable .....
### Our problem is basically a  supervised regreession problem of machine learning ..... 

In [290]:
X = df_copy.drop(['charging_duration_min'],axis = 1)
## creating a copy of X (independent variables) as X_copy
y = df_copy[['charging_duration_min']]
X_copy = X.copy()

In [291]:
print(len(X.columns))

73


In [292]:
print(X.columns)

Index(['session_id', 'vehicle_id', 'user_id', 'start_time', 'end_time',
       'energy_delivered_kwh', 'vehicle_make', 'vehicle_model',
       'battery_capacity_kwh', 'vehicle_age_years', 'battery_health_index',
       'user_type', 'income_bracket', 'city', 'state', 'latitude', 'longitude',
       'charging_station_id', 'station_operator', 'charger_type',
       'charger_power_kw', 'plug_type', 'initial_soc_percent',
       'final_soc_percent', 'soc_gained_percent', 'day_of_week', 'hour_of_day',
       'month', 'season', 'is_weekend', 'is_peak_hour', 'festival',
       'ambient_temperature_c', 'humidity_percent', 'weather_condition',
       'air_quality_index', 'battery_temperature_c', 'grid_frequency_hz',
       'grid_reliability_index', 'power_quality_score', 'load_shedding_event',
       'grid_load_mw', 'tariff_per_kwh_inr', 'total_cost_inr',
       'subsidy_amount_inr', 'payment_method', 'payment_success_rate',
       'station_congestion_level', 'queue_wait_time_min',
       'charg

### converting the dataframe into 1 dimensional array  (target_variable)

In [293]:
y = y.iloc[:,0].to_numpy() ## target variable is converted from dataframe to 1d array 

In [294]:
y

array([ 38.36666667, 145.        ,  11.75      , ...,   5.36666667,
        51.6       ,  17.66666667])

In [295]:
X.shape,y.shape,X_copy.shape

((74943, 73), (74943,), (74943, 73))

## Lets do a data preprocessing and feature engineering on the dataset

### Dropping the columns which are not required for analysis
- session_id
- vehicle_id
- user_id
- latitude
- longitude
- charging_station_id
- festival
- payment_method
- payment_success_rate
- app_reliability_rating
- state_ev_policy
- charging_standard_compliance
- safety_certification
- is_month_end
- is_quarter_end
- vehicle_make 
- day_of_week  
- city   
- month  
- state  
- hour_of_day  
- tariff_per_kwh_inr  
- subsidy_amount_inr 
- session_success_rate 
- user_satisfaction_score 
- session_rating  
- energy_efficiency_kwh_per_100km  
- trip_purpose  
- is_weekend  


In [296]:
X_copy.drop(columns=['session_id', 'vehicle_id', 'user_id','latitude', 'longitude',
       'charging_station_id','festival','payment_method', 'payment_success_rate','app_reliability_rating', 'state_ev_policy',
       'charging_standard_compliance', 'safety_certification','is_month_end', 'is_quarter_end','vehicle_make','day_of_week','city',
       'month','state','hour_of_day','tariff_per_kwh_inr','subsidy_amount_inr','session_success_rate','user_satisfaction_score','session_rating','energy_efficiency_kwh_per_100km','trip_purpose','is_weekend'], inplace=True)


In [297]:
X_copy.shape,X.shape

((74943, 44), (74943, 73))

### Now we are going to the label Encoder part 
- is_peak_hour
- is_weekend
- load_shedding_event
- Cooling_system_active
- Station_operator

In [298]:
from sklearn.preprocessing import LabelEncoder

In [299]:
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()
le4=LabelEncoder()
le5=LabelEncoder()

In [300]:
import warnings
warnings.filterwarnings('ignore')
X_copy['vehicle_model']=le1.fit_transform(X_copy['vehicle_model'])
X_copy['is_peak_hour']=le2.fit_transform(X_copy['is_peak_hour'])
X_copy['load_shedding_event']=le3.fit_transform(X_copy['load_shedding_event'])
X_copy['cooling_system_active']=le4.fit_transform(X_copy['cooling_system_active'])
X_copy['station_operator']=le5.fit_transform(X_copy['station_operator'])

In [301]:
X_copy['vehicle_model'].unique(),X_copy['is_peak_hour'].unique(),X_copy['load_shedding_event'].unique(),X_copy['cooling_system_active'].unique(),X_copy['station_operator'].unique()

(array([21, 14, 18, 15, 13, 19, 23, 27, 16, 22, 10, 26, 25, 11,  4,  3,  8,
         1, 24, 17,  0, 12,  6,  9,  7,  5,  2, 20]),
 array([1, 0], dtype=int64),
 array([0, 1]),
 array([0, 1]),
 array([ 1,  8,  9,  2,  6, 10,  5,  0,  4,  3,  7]))

In [302]:
X_copy.shape,X.shape

((74943, 44), (74943, 73))

In [303]:
X_copy.columns

Index(['start_time', 'end_time', 'energy_delivered_kwh', 'vehicle_model',
       'battery_capacity_kwh', 'vehicle_age_years', 'battery_health_index',
       'user_type', 'income_bracket', 'station_operator', 'charger_type',
       'charger_power_kw', 'plug_type', 'initial_soc_percent',
       'final_soc_percent', 'soc_gained_percent', 'season', 'is_peak_hour',
       'ambient_temperature_c', 'humidity_percent', 'weather_condition',
       'air_quality_index', 'battery_temperature_c', 'grid_frequency_hz',
       'grid_reliability_index', 'power_quality_score', 'load_shedding_event',
       'grid_load_mw', 'total_cost_inr', 'station_congestion_level',
       'queue_wait_time_min', 'charger_utilization_rate',
       'station_uptime_percent', 'charging_efficiency_percent',
       'charging_curve_efficiency', 'cooling_system_active',
       'thermal_management', 'distance_to_station_km', 'range_remaining_km',
       'next_destination_distance_km', 'session_type', 'booking_lead_time_min',
  

In [304]:
#'user_type','charger_type','plug_type','season','weather_condition','session_type'
df['user_type'].value_counts(normalize=True), df['charger_type'].value_counts(normalize=True),df['plug_type'].value_counts(normalize=True),df['season'].value_counts(normalize=True), df['weather_condition'].value_counts(normalize=True), df['session_type'].value_counts(normalize=True)

(user_type
 Private       0.450622
 Fleet         0.201046
 Taxi          0.148700
 Ride_Share    0.099582
 Delivery      0.080181
 Government    0.019868
 Name: proportion, dtype: float64,
 charger_type
 AC_SLOW    0.602565
 AC_FAST    0.247628
 DC_FAST    0.149807
 Name: proportion, dtype: float64,
 plug_type
 Type2           0.299014
 CCS2            0.250951
 Bharat AC001    0.200592
 CHAdeMO         0.149554
 Bharat DC001    0.099889
 Name: proportion, dtype: float64,
 season
 Summer          0.334975
 Monsoon         0.252805
 Winter          0.246027
 Post_Monsoon    0.166193
 Name: proportion, dtype: float64,
 weather_condition
 Clear            0.397302
 PARTLY_CLOUDY    0.200165
 Overcast         0.150488
 LIGHT_RAIN       0.100703
 HEAVY_RAIN       0.051092
 THUNDERSTORM     0.029969
 Foggy            0.029502
 DUST_STORM       0.020656
 HEATWAVE         0.020122
 Name: proportion, dtype: float64,
 session_type
 Opportunistic    0.550832
 Scheduled        0.398570
 Emergency

### Now we are goint to the One hot encoding world !!!! 
- user_type
- charger_type
- plug_type
- season
- weather_condition
- session_type

In [305]:
## Onehot encoding--- ColumnTrnasformer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [306]:
onehot_columns = ['user_type','charger_type','plug_type','season','weather_condition','session_type']
# Apply One-Hot Encoding only to those columns
X_copy_encoded = pd.get_dummies(X_copy, columns=onehot_columns, drop_first=True,dtype=int)

# Overwrite the original DataFrame with the updated one
X_copy = X_copy_encoded

In [307]:
X_copy.shape,X.shape

((74943, 62), (74943, 73))

In [308]:
X_copy.columns

Index(['start_time', 'end_time', 'energy_delivered_kwh', 'vehicle_model',
       'battery_capacity_kwh', 'vehicle_age_years', 'battery_health_index',
       'income_bracket', 'station_operator', 'charger_power_kw',
       'initial_soc_percent', 'final_soc_percent', 'soc_gained_percent',
       'is_peak_hour', 'ambient_temperature_c', 'humidity_percent',
       'air_quality_index', 'battery_temperature_c', 'grid_frequency_hz',
       'grid_reliability_index', 'power_quality_score', 'load_shedding_event',
       'grid_load_mw', 'total_cost_inr', 'station_congestion_level',
       'queue_wait_time_min', 'charger_utilization_rate',
       'station_uptime_percent', 'charging_efficiency_percent',
       'charging_curve_efficiency', 'cooling_system_active',
       'thermal_management', 'distance_to_station_km', 'range_remaining_km',
       'next_destination_distance_km', 'booking_lead_time_min', 'week_of_year',
       'day_of_year', 'user_type_Fleet', 'user_type_Government',
       'user_type

### Now we are going to the label Encoder part 
- is_peak_hour
- load_shedding_event
- Cooling_system_active

In [309]:
#income_bracket
#station_congestion_level
#thermal_management
# Example: encoding education levels manually
income_bracket_order= {'High':5, 'Upper_Middle':4, 'Middle':3, 'Lower_Middle':2,'Low':1}
station_congestion_level_order= {'High':3, 'Medium':2, 'Low':1}
thermal_management_order =  {'Active':2, 'Passive':1}
# Apply encoding
X_copy['income_bracket'] = X_copy['income_bracket'].map(income_bracket_order)
X_copy['station_congestion_level'] = X_copy['station_congestion_level'].map(station_congestion_level_order)
X_copy['thermal_management'] = X_copy['thermal_management'].map(thermal_management_order)

# These changes are saved directly in the original DataFrame

In [310]:
X_copy['income_bracket'].value_counts(normalize=True)*100,X_copy['station_congestion_level'].value_counts(normalize=True)*100,X_copy['thermal_management'].value_counts(normalize=True)*100

(income_bracket
 3    35.083997
 2    24.792175
 4    20.107282
 5    10.068986
 1     9.947560
 Name: proportion, dtype: float64,
 station_congestion_level
 1    50.108749
 2    34.871836
 3    15.019415
 Name: proportion, dtype: float64,
 thermal_management
 1    73.082209
 2    26.917791
 Name: proportion, dtype: float64)

### Spliting the Start_time and end_time columns into  and drop the end_time and start_time column
-  start_time_day
-  start_time_month
-  start_time_year
-  start_time_hour
-  start_time_minute
-  end_time_day
-  end_time_month
-  end_time_year
-  end_time_hour
-  end_time_minute

In [311]:
X_copy['start_time_day']= X_copy['start_time'].str.split(' ').str[0].str.split('-').str[0]
X_copy['start_time_month']= X_copy['start_time'].str.split(' ').str[0].str.split('-').str[1]
X_copy['start_time_year']= X_copy['start_time'].str.split(' ').str[0].str.split('-').str[2]
X_copy['start_time_hr']= X_copy['start_time'].str.split(' ').str[1].str.split(':').str[0]
X_copy['start_time_min']= X_copy['start_time'].str.split(' ').str[1].str.split(':').str[1]


In [312]:
X_copy['end_time_day']= X_copy['end_time'].str.split(' ').str[0].str.split('-').str[0]
X_copy['end_time_month']= X_copy['end_time'].str.split(' ').str[0].str.split('-').str[1]
X_copy['end_time_year']= X_copy['end_time'].str.split(' ').str[0].str.split('-').str[2]
X_copy['end_time_hr']= X_copy['end_time'].str.split(' ').str[1].str.split(':').str[0]
X_copy['end_time_min']= X_copy['end_time'].str.split(' ').str[1].str.split(':').str[1]


In [313]:
X_copy['start_time_day']=X_copy['start_time_day'].astype(int)
X_copy['start_time_month']=X_copy['start_time_month'].astype(int)
X_copy['start_time_year']=X_copy['start_time_year'].astype(int)
X_copy['start_time_hr']=X_copy['start_time_hr'].astype(int)
X_copy['start_time_min']=X_copy['start_time_min'].astype(int)
X_copy['end_time_day']=X_copy['end_time_day'].astype(int)
X_copy['end_time_month']=X_copy['end_time_month'].astype(int)
X_copy['end_time_year']=X_copy['end_time_year'].astype(int)
X_copy['end_time_hr']=X_copy['end_time_hr'].astype(int)
X_copy['end_time_min']=X_copy['end_time_min'].astype(int)


In [314]:
X_copy.drop(columns=['start_time', 'end_time'], inplace=True)

In [315]:
X_copy.shape , X.shape

((74943, 70), (74943, 73))

In [316]:
X_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74943 entries, 0 to 74942
Data columns (total 70 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   energy_delivered_kwh             74943 non-null  float64
 1   vehicle_model                    74943 non-null  int32  
 2   battery_capacity_kwh             74943 non-null  float64
 3   vehicle_age_years                74943 non-null  int64  
 4   battery_health_index             74943 non-null  float64
 5   income_bracket                   74943 non-null  int64  
 6   station_operator                 74943 non-null  int32  
 7   charger_power_kw                 74943 non-null  float64
 8   initial_soc_percent              74943 non-null  int64  
 9   final_soc_percent                74943 non-null  int64  
 10  soc_gained_percent               74943 non-null  int64  
 11  is_peak_hour                     74943 non-null  int64  
 12  ambient_temperatur

### Train test split is our task so we divide our data set into train and test set 
### Testing is 20 percent of the complete dataset
### Training is 80 percent of the complete dataset

In [ ]:
##train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_copy,y,test_size=0.20,random_state=42)

In [318]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((59954, 70), (14989, 70), (59954,), (14989,))

In [319]:
X_train.head(1)

,energy_delivered_kwh,vehicle_model,battery_capacity_kwh,vehicle_age_years,battery_health_index,income_bracket,station_operator,charger_power_kw,initial_soc_percent,final_soc_percent,...,start_time_day,start_time_month,start_time_year,start_time_hr,start_time_min,end_time_day,end_time_month,end_time_year,end_time_hr,end_time_min
17614,8.065,14,26.0,0,1.017,2,7,6.5,10,38,...,18,8,2019,21,30,18,8,2019,23,1


In [320]:
X_test.head(1)

,energy_delivered_kwh,vehicle_model,battery_capacity_kwh,vehicle_age_years,battery_health_index,income_bracket,station_operator,charger_power_kw,initial_soc_percent,final_soc_percent,...,start_time_day,start_time_month,start_time_year,start_time_hr,start_time_min,end_time_day,end_time_month,end_time_year,end_time_hr,end_time_min
2675,0.668,15,2.9,11,0.754,3,3,19.9,28,57,...,1,4,2018,16,22,1,4,2018,16,27


In [321]:
y_train,y_test

(array([ 91.05      , 200.3333333 ,  12.48333333, ...,  10.26666667,
         81.58333333,  52.        ]),
 array([ 5.        , 37.61666667, 14.15      , ...,  5.03333333,
         8.98333333,  9.9       ]))

In [322]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59954 entries, 17614 to 50496
Data columns (total 70 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   energy_delivered_kwh             59954 non-null  float64
 1   vehicle_model                    59954 non-null  int32  
 2   battery_capacity_kwh             59954 non-null  float64
 3   vehicle_age_years                59954 non-null  int64  
 4   battery_health_index             59954 non-null  float64
 5   income_bracket                   59954 non-null  int64  
 6   station_operator                 59954 non-null  int32  
 7   charger_power_kw                 59954 non-null  float64
 8   initial_soc_percent              59954 non-null  int64  
 9   final_soc_percent                59954 non-null  int64  
 10  soc_gained_percent               59954 non-null  int64  
 11  is_peak_hour                     59954 non-null  int64  
 12  ambient_temperature

In [323]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14989 entries, 2675 to 45015
Data columns (total 70 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   energy_delivered_kwh             14989 non-null  float64
 1   vehicle_model                    14989 non-null  int32  
 2   battery_capacity_kwh             14989 non-null  float64
 3   vehicle_age_years                14989 non-null  int64  
 4   battery_health_index             14989 non-null  float64
 5   income_bracket                   14989 non-null  int64  
 6   station_operator                 14989 non-null  int32  
 7   charger_power_kw                 14989 non-null  float64
 8   initial_soc_percent              14989 non-null  int64  
 9   final_soc_percent                14989 non-null  int64  
 10  soc_gained_percent               14989 non-null  int64  
 11  is_peak_hour                     14989 non-null  int64  
 12  ambient_temperature_

In [324]:
X_train.columns

Index(['energy_delivered_kwh', 'vehicle_model', 'battery_capacity_kwh',
       'vehicle_age_years', 'battery_health_index', 'income_bracket',
       'station_operator', 'charger_power_kw', 'initial_soc_percent',
       'final_soc_percent', 'soc_gained_percent', 'is_peak_hour',
       'ambient_temperature_c', 'humidity_percent', 'air_quality_index',
       'battery_temperature_c', 'grid_frequency_hz', 'grid_reliability_index',
       'power_quality_score', 'load_shedding_event', 'grid_load_mw',
       'total_cost_inr', 'station_congestion_level', 'queue_wait_time_min',
       'charger_utilization_rate', 'station_uptime_percent',
       'charging_efficiency_percent', 'charging_curve_efficiency',
       'cooling_system_active', 'thermal_management', 'distance_to_station_km',
       'range_remaining_km', 'next_destination_distance_km',
       'booking_lead_time_min', 'week_of_year', 'day_of_year',
       'user_type_Fleet', 'user_type_Government', 'user_type_Private',
       'user_type_Ride

In [325]:
# Create Column Transformer with 3 types of transformers
num_features= ['energy_delivered_kwh','battery_capacity_kwh',
       'vehicle_age_years', 'battery_health_index' ,'charger_power_kw', 'initial_soc_percent',
       'final_soc_percent', 'soc_gained_percent',
       'ambient_temperature_c', 'humidity_percent', 'air_quality_index',
       'battery_temperature_c', 'grid_frequency_hz', 'grid_reliability_index',
       'power_quality_score','grid_load_mw',
       'total_cost_inr','queue_wait_time_min',
       'charger_utilization_rate', 'station_uptime_percent',
       'charging_efficiency_percent', 'charging_curve_efficiency','distance_to_station_km',
       'range_remaining_km', 'next_destination_distance_km',
       'booking_lead_time_min', 'week_of_year', 'day_of_year']

from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()


preprocessor = ColumnTransformer(
    [
        ("StandardScaler", numeric_transformer, num_features)
    ],remainder='passthrough'
    
)

In [326]:
X_train_scaled = X_train.copy()
X_train_scaled[num_features]=numeric_transformer.fit_transform(X_train[num_features]) ## using fit_transform here
X_test_scaled = X_test.copy()
X_test_scaled[num_features]=numeric_transformer.transform(X_test[num_features]) ## using only transform here
## summation of (data point - mean / standard deviaition)

In [327]:
X_train_scaled.shape

(59954, 70)

In [328]:
X_train_scaled.head()

,energy_delivered_kwh,vehicle_model,battery_capacity_kwh,vehicle_age_years,battery_health_index,income_bracket,station_operator,charger_power_kw,initial_soc_percent,final_soc_percent,...,start_time_day,start_time_month,start_time_year,start_time_hr,start_time_min,end_time_day,end_time_month,end_time_year,end_time_hr,end_time_min
17614,0.097796,14,0.370405,-0.815828,1.356553,2,7,-0.440692,-1.707224,-2.269456,...,18,8,2019,21,30,18,8,2019,23,1
64594,0.495750,25,0.817174,1.989388,-1.632129,3,1,-0.534011,0.223283,0.281667,...,8,1,2024,21,2,9,1,2024,0,22
73876,-0.382694,24,0.118112,3.993114,-3.556093,3,6,-0.079861,1.268974,0.208777,...,23,11,2024,11,40,23,11,2024,11,53
10235,-0.837280,3,-0.838499,-0.815828,1.132402,3,5,-0.524679,-0.420220,-1.613453,...,13,12,2018,12,28,13,12,2018,12,44
57591,1.110330,8,1.132540,-0.815828,0.198439,3,5,-0.425139,-0.581095,-0.301447,...,11,5,2023,23,34,12,5,2023,2,5


In [329]:
X_train.head()

,energy_delivered_kwh,vehicle_model,battery_capacity_kwh,vehicle_age_years,battery_health_index,income_bracket,station_operator,charger_power_kw,initial_soc_percent,final_soc_percent,...,start_time_day,start_time_month,start_time_year,start_time_hr,start_time_min,end_time_day,end_time_month,end_time_year,end_time_hr,end_time_min
17614,8.065,14,26.0,0,1.017,2,7,6.5,10,38,...,18,8,2019,21,30,18,8,2019,23,1
64594,11.199,25,34.5,7,0.857,3,1,3.5,34,73,...,8,1,2024,21,2,9,1,2024,0,22
73876,4.281,24,21.2,12,0.754,3,6,18.1,47,72,...,23,11,2024,11,40,23,11,2024,11,53
10235,0.701,3,3.0,0,1.005,3,5,3.8,26,47,...,13,12,2018,12,28,13,12,2018,12,44
57591,16.039,8,40.5,0,0.955,3,5,7.0,24,65,...,11,5,2023,23,34,12,5,2023,2,5


### Making csv file of X_train_copy , y_train and y_test 

In [330]:
X_train_scaled.to_csv(r"./data/X_train.csv", index=False)

In [331]:
import numpy as np

# Save y_train
np.savetxt(r"./data/y_train.csv", y_train, delimiter=",", fmt='%s')



In [332]:
X_test_scaled.to_csv(r"./data/X_test.csv", index=False)

In [333]:
import numpy as np

# Save y_test
np.savetxt(r"./data/y_test.csv", y_test, delimiter=",", fmt='%s')




In [334]:
X_train.columns

Index(['energy_delivered_kwh', 'vehicle_model', 'battery_capacity_kwh',
       'vehicle_age_years', 'battery_health_index', 'income_bracket',
       'station_operator', 'charger_power_kw', 'initial_soc_percent',
       'final_soc_percent', 'soc_gained_percent', 'is_peak_hour',
       'ambient_temperature_c', 'humidity_percent', 'air_quality_index',
       'battery_temperature_c', 'grid_frequency_hz', 'grid_reliability_index',
       'power_quality_score', 'load_shedding_event', 'grid_load_mw',
       'total_cost_inr', 'station_congestion_level', 'queue_wait_time_min',
       'charger_utilization_rate', 'station_uptime_percent',
       'charging_efficiency_percent', 'charging_curve_efficiency',
       'cooling_system_active', 'thermal_management', 'distance_to_station_km',
       'range_remaining_km', 'next_destination_distance_km',
       'booking_lead_time_min', 'week_of_year', 'day_of_year',
       'user_type_Fleet', 'user_type_Government', 'user_type_Private',
       'user_type_Ride

In [335]:
X_train.corr()

,energy_delivered_kwh,vehicle_model,battery_capacity_kwh,vehicle_age_years,battery_health_index,income_bracket,station_operator,charger_power_kw,initial_soc_percent,final_soc_percent,...,start_time_day,start_time_month,start_time_year,start_time_hr,start_time_min,end_time_day,end_time_month,end_time_year,end_time_hr,end_time_min
energy_delivered_kwh,1.000000,0.131492,0.904613,-0.047472,0.051577,-0.000388,0.001450,-0.002440,-0.122825,0.170019,...,-0.003274,0.009830,-0.001325,0.005958,-0.006564,-0.004678,0.010280,-0.001308,0.001514,0.002929
vehicle_model,0.131492,1.000000,0.140077,-0.000709,0.000753,0.005346,-0.004762,0.005227,0.000107,0.002513,...,-0.004025,-0.004314,-0.005497,-0.002171,0.003464,-0.003436,-0.004302,-0.005498,-0.001517,0.005079
battery_capacity_kwh,0.904613,0.140077,1.000000,-0.002460,0.002238,0.002502,0.000679,-0.001650,0.001695,-0.003242,...,-0.003433,0.000546,-0.003529,0.003596,-0.005614,-0.005287,0.000964,-0.003508,0.000788,0.003868
vehicle_age_years,-0.047472,-0.000709,-0.002460,1.000000,-0.925583,0.004242,0.008201,0.000043,-0.004779,-0.001839,...,0.000272,0.002514,-0.001592,0.005100,0.000619,-0.000606,0.002575,-0.001592,0.003118,0.003916
battery_health_index,0.051577,0.000753,0.002238,-0.925583,1.000000,-0.003197,-0.008118,0.002780,0.004709,0.002565,...,-0.001324,0.000505,-0.000188,-0.003710,-0.000428,-0.000381,0.000472,-0.000193,-0.000342,-0.002867
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
end_time_day,-0.004678,-0.003436,-0.005287,-0.000606,-0.000381,-0.000247,0.003993,-0.001900,-0.001038,-0.000301,...,0.990745,0.010145,0.008586,-0.001850,-0.000726,1.000000,0.009561,0.008558,0.000446,0.003846
end_time_month,0.010280,-0.004302,0.000964,0.002575,0.000472,0.001181,-0.002247,-0.007581,0.000548,0.000147,...,0.009670,0.999763,-0.000214,0.006307,-0.002577,0.009561,1.000000,-0.000241,0.005920,0.000092
end_time_year,-0.001308,-0.005498,-0.003508,-0.001592,-0.000193,0.003786,-0.006215,-0.006165,-0.002830,-0.000491,...,0.008656,-0.000100,0.999996,-0.005817,-0.003699,0.008558,-0.000241,1.000000,-0.005772,0.001438
end_time_hr,0.001514,-0.001517,0.000788,0.003118,-0.000342,-0.007486,0.002383,0.005199,-0.001882,-0.007851,...,-0.000324,0.006458,-0.005750,0.772835,0.004567,0.000446,0.005920,-0.005772,1.000000,-0.001466
